export default [
  {
    title: 'hooshen.gg',
    description:
      "Website made for a client. He's a map creator for a videogame called Fortnite and wanted a website to showcase all his maps divided by categories. Made completely with React Hooks and SCSS.",
    tech: [
      'React',
      'React Hooks',
      'JavaScript',
      'JSX',
      'JSON',
      'SCSS',
      'Node.js',
    ],
    demo: 'https://hooshen.gg/',
    thumbnail: '/img/portfolio/hooshen-gg.jpg',
    image: '/img/portfolio/hooshen-gg.jpg',
    id: 'hooshen-gg',
    // github: "https://github.com/naknekv/hooshen-maps"
  },
  {
    title: 'E-Commerce App',
    description:
      'Practice E-Commerce website in which I used Redux for state management and Firebase for Auth, the cart is stored in Local Storage. All the CSS was done with SCSS.',
    tech: [
      'React',
      'React Hooks',
      'Redux',
      'Firebase',
      'JavaScript',
      'JSX',
      'JSON',
      'SCSS',
      'Node.js',
      'Local Storage',
    ],
    demo: 'https://react-e-commerce-nak.herokuapp.com/',
    thumbnail: '/img/portfolio/e-commerce-app.jpg',
    image: '/img/portfolio/e-commerce-app.jpg',
    id: 'e-commerce-app',
    github: 'https://github.com/naknekv/react-e-commerce',
  },
  {
    title: 'Barcelona Restaurant Search',
    description:
      'Practice Native App for Android/iOS. You can search for any restaraunt in the Barcelona Area and you get them sorted out by price. You can also see the address and the phone number. It was done with React Native and the Expo CLI.',
    tech: ['React Native', 'Expo CLI', 'Axios', 'JavaScript', 'JSX', 'Node.js'],
    demo: '/files/ignacio-iacovino-restaurant-app.apk',
    thumbnail: '/img/portfolio/barcelona-restaurant-search-thumb.jpg',
    image: '/img/portfolio/barcelona-restaurant-search.jpg',
    id: 'barcelona-restaurant-search',
    github: 'https://github.com/naknekv/React-Native-Restaurant-Seach',
  },
  {
    title: 'Todo App with Hooks',
    description:
      'Todo App made with React and the Context API, the TODOs are saved in Local Storage. The reducer for the context use CRUD.',
    tech: [
      'React',
      'React Hooks',
      'Context API',
      'JavaScript',
      'JSX',
      'JSON',
      'Material UI',
      'Node.js',
      'Local Storage',
    ],
    demo: 'https://todo-app-nak.herokuapp.com/',
    thumbnail: '/img/portfolio/todo-app.jpg',
    image: '/img/portfolio/todo-app.jpg',
    id: 'todo-app',
    github: 'https://github.com/naknekv/react-hooks-todo-app',
  },
  {
    title: 'Yahtzee',
    description:
      "The classic game 'Yahtzee' made with React, you throw the dice and try to get a high score by combining the results.",
    tech: ['React', 'JavaScript', 'JSX', 'CSS3', 'Node.js'],
    demo: 'https://yahtzee-nak.herokuapp.com/',
    thumbnail: '/img/portfolio/yahtzee.jpg',
    image: '/img/portfolio/yahtzee.jpg',
    id: 'yahtzee',
    github: 'https://github.com/naknekv/react-yahtzee',
  },
  {
    title: 'Lights out',
    description:
      "The classic game 'Lights Out' made with React. When you click on a square, it switches itself and the surrounding squares, the objective of the game is turn all of the squares off.",
    tech: ['React', 'JavaScript', 'JSX', 'CSS3', 'Node.js'],
    demo: 'https://lights-out-nak.herokuapp.com/',
    thumbnail: 'img/portfolio/lights-out.jpg',
    image: 'img/portfolio/lights-out.jpg',
    id: 'lights-out',
    github: 'https://github.com/naknekv/react-lights-out',
  },
];
